// Generated file, do not manually edit. Generate from BE instead (php artisan app:generate-permission-constants)
export const Permissions = {
  VIEW_HORIZON_DASHBOARD: 'view_horizon_dashboard',
  MANAGE_USERS: 'manage_users',
  BROWSE_USERS: 'browse_users',
  READ_USER: 'read_user',
  EDIT_USER: 'edit_user',
  ADD_USER: 'add_user',
  DELETE_USER: 'delete_user',
  MANAGE_ORDINARY_USERS: 'manage_ordinary_users',
  BROWSE_ORDINARY_USERS: 'browse_ordinary_users',
  READ_ORDINARY_USER: 'read_ordinary_user',
  VERIFY_ORDINARY_USER: 'verify_ordinary_user',
  MANAGE_PERMITS: 'manage_permits',
  BROWSE_PERMITS: 'browse_permits',
  READ_PERMIT: 'read_permit',
  EDIT_PERMIT: 'edit_permit',
  ADD_PERMIT: 'add_permit',
  DELETE_PERMIT: 'delete_permit',
  SET_PERMIT_STATE_PENDING: 'set_permit_state_pending',
  SET_PERMIT_STATE_REVISION: 'set_permit_state_revision',
  SET_PERMIT_STATE_APPROVED: 'set_permit_state_approved',
  SET_PERMIT_STATE_REJECTED: 'set_permit_state_rejected',
  SET_PERMIT_STATE_CANCELED: 'set_permit_state_canceled',
  MANAGE_PERMIT_REVIEWS: 'manage_permit_reviews',
  BROWSE_PERMIT_REVIEWS: 'browse_permit_reviews',
  READ_PERMIT_REVIEW: 'read_permit_review',
  EDIT_PERMIT_REVIEW: 'edit_permit_review',
  ADD_PERMIT_REVIEW: 'add_permit_review',
  DELETE_PERMIT_REVIEW: 'delete_permit_review',
};
